{{- $fullName := include "transmission.fullname" . -}}
{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-data
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  {{- if .Values.persistentVolume.annotations }}
  annotations:
    {{- .Values.persistentVolume.annotaions | toYaml | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- .Values.persistentVolume.accessModes | toYaml | nindent 4 }}
{{- if .Values.persistentVolume.storageClass }}
{{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-media
  labels:
    type: transmission-media-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "transmission-media"
  resources:
    requests:
      storage: 1Ti

